In [306]:
import re
import pandas as pd


df = pd.read_csv('C:\\Users\\ryan\\Desktop\\Thinkful DS Sample Data - Main Course\\WELLCOME_APCspend2013_forThinkful3.csv')
df.head()

,PMID/PMCID,Publisher,Journal title,Article title,COST () charged to Wellcome (inc VAT when charged)
0,NaN,CUP,Psychological Medicine,Reduced parahippocampal cortical thickness in ...,0.00
1,PMC3679557,ACS,Biomacromolecules,Structural characterization of a Model Gram-ne...,"2,381.04"
2,23043264 PMC3506128,ACS,J Med Chem,"Fumaroylamino-4,5-epoxymorphinans and related ...",642.56
3,23438330 PMC3646402,ACS,J Med Chem,Orvinols with mixed kappa/mu opioid receptor a...,669.64
4,23438216 PMC3601604,ACS,J Org Chem,Regioselective opening of myo-inositol orthoes...,685.88

In [307]:
#Explore the data with a groupby to help visualize some of the problems
df2 = df.groupby('Journal title').count()
df2.head(1000)
#print(df2)
#Will need to clear spaces before and after, remove commas and semicolons, capitalize all titles

,PMID/PMCID,Publisher,Article title,COST () charged to Wellcome (inc VAT when charged)
Journal title,,,,
ACS Chemical Biology,4,5,5,5
ACS Chemical Neuroscience,1,1,1,1
ACS NANO,1,1,1,1
ACS Nano,1,1,1,1
ACTA F,1,1,1,1
AGE,1,1,1,1
AIDS,3,3,3,3
AIDS Behav,1,1,1,1
AIDS Care,2,2,2,2
AIDS Journal,1,1,1,1
AIDS Research and Therapy,1,1,1,1
AIDS UK,2,2,2,2
ASN Neuro,0,1,1,1
Academy of Nutrition and Dietetics,1,1,1,1
"Acta Crystallographica Section D, Biological Crystallography",1,1,1,1
Acta Crystallographica Section D: Biological Crystallography,1,1,1,1
Acta Crystallographica Section F: Structural Biology and Crystallization Communications,2,2,2,2
"Acta Crystallographica, Section D",1,1,1,1
Acta Crystallography D,1,1,1,1
Acta D,1,1,1,1
Acta Dermato Venereologica,1,1,1,1
Acta Diabetologica,1,1,1,1
Acta Neuropathol,1,1,1,1
Acta Neuropathologica,2,3,3,3
Acta Opthalmologica,1,1,1,1
Acta Physiol,1,1,1,1
Addiction,2,2,2,2
Advances in Experimental Medicine and Biology,0,4,4,4
Age,1,1,1,1
Age and Ageing,1,1,1,1
...,...,...,...,...
Translational Psychiatry,2,2,2,2
Trends in Cognitive Science,1,1,1,1
Trends in Genetics,2,2,2,2
Trends in Microbiology,1,1,1,1
Trends in Molecular Medicine,1,1,1,1
Trends in Neuroscience,1,1,1,1
Trends in Neurosciences,1,2,2,2
Trends in Parasitology,0,4,4,4
Trials,4,4,4,4
Trials,1,1,1,1
Trop Med Int Health,1,1,1,1
Tropical Animal Health & Production,1,1,1,1
Tropical Medicine and International Health,5,6,6,6
Tuberculosis,2,2,2,2
Urban History,0,1,1,1
Urolithiasis,1,1,1,1
Vaccine,5,5,5,5
Vascular Pharmacology,1,1,1,1
Veterinary Microbiology,1,1,1,1
Veterinary Parasitology,1,2,2,2
Veterinary Record,1,1,1,1
Veterinary Research,1,1,1,1
Virology,2,2,2,2
Virology Journal,1,1,1,1
Virus Research,1,1,1,1
Vision Research,2,2,2,2
Visual Neuroscience,1,1,1,1
Zoonoses and Public Health,1,1,1,1
genesis: Journal of Genetics,1,1,1,1
mBio,1,1,1,1

In [360]:
#Remove blank spaces before and after Journal title
df['Journal Title 2'] = df['Journal title'].apply(lambda x: str(x).strip())
#Remove commas and colons
df['Journal Title 3'] = df['Journal Title 2'].apply(lambda x: str(x).replace(':', ''))
df['Journal Title 4'] = df['Journal Title 3'].apply(lambda x: str(x).replace(',', ''))
#Put everything in all caps
df['Journal Title 5'] = df['Journal Title 4'].apply(lambda x: str(x).upper())
#Remove all text after " Section" to better group journals together
df['Journal Title 6'] = df['Journal Title 5'].apply(lambda x: str(x).split(' SECTION', 1)[0])
#Replace all " J " with "Journal"
df['Journal Title 7'] = df['Journal Title 6'].apply(lambda x: str(x).replace('J ', 'JOURNAL '))
df['Journal Title 8'] = df['Journal Title 7'].apply(lambda x: str(x).strip())
 
#Remove commas, $ signs from cost
df['Cost New'] = df['COST () charged to Wellcome (inc VAT when charged)'].apply(lambda x: str(x).replace(',', ''))
df['Cost New 2'] = df['Cost New'].apply(lambda x: str(x).replace('$', ''))
#Convert cost variable from string to a float to allow for mathematical operations
df['Cost New 3'] = df['Cost New 2'].apply(lambda x: float(x))

#print(df['Cost New 3'].max())
#Some cost amounts are 999.9K - exclude these, replace with NaN and drop
df['Cost New 4'] = df['Cost New 3'].replace(999999.00, np.nan)

df = df.dropna()

#############****Replace 9999999 with NaN from np...up for debate as to whether 0 is better, 
#then drop the NaN values using .dropna() from pandas. Leave the zeros in there - they may be valid. 


#print(df['Cost New 4'].min())
#Some cost amounts are 0 - leave these in here as they could be valid


#Could do more cleaning if this were a "real" work project, but this is sufficient for now

#Sort by number of articles published
#df2 = df.groupby('Journal Title 8', as_index = False).count()
#df3 = df2.sort_values('Journal Title 7', ascending = False)
#df3.head()

In [361]:
#Calculate mean, median, and mode

df5 = pd.DataFrame()
df5['Journal'] = df['Journal Title 8']
df5['Cost'] = df['Cost New 4']
#df5.head()
#df5[df5['Journal'] == 'JOURNAL MED CHEM']
#df2[df2['Journal Title 8'] == 'JOURNAL MED CHEM']
df_count = df5.groupby('Journal', as_index = False).count()
df_count.head()

                              Journal  Cost
0  ACADEMY OF NUTRITION AND DIETETICS     1
1                ACS CHEMICAL BIOLOGY     4
2           ACS CHEMICAL NEUROSCIENCE     1
3                            ACS NANO     2
4              ACTA CRYSTALLOGRAPHICA     5

In [362]:
df_mean = df5.groupby('Journal', as_index = False).mean()
df_mean.head()

                              Journal      Cost
0  ACADEMY OF NUTRITION AND DIETETICS  2379.540
1                ACS CHEMICAL BIOLOGY  1535.965
2           ACS CHEMICAL NEUROSCIENCE  1186.800
3                            ACS NANO   668.140
4              ACTA CRYSTALLOGRAPHICA   779.122

In [363]:
df_med = df5.groupby('Journal', as_index = False).median()
df_med.head()

                              Journal      Cost
0  ACADEMY OF NUTRITION AND DIETETICS  2379.540
1                ACS CHEMICAL BIOLOGY  1294.685
2           ACS CHEMICAL NEUROSCIENCE  1186.800
3                            ACS NANO   668.140
4              ACTA CRYSTALLOGRAPHICA   773.740

In [371]:
df_std = df5.groupby('Journal').std(ddof=0)
#df_std.head()
#df5.std()
df_std.head()

### Need to JOIN std dev cost column over to df_final (see below)
merged = pd.merge(df_std, df_count, left_index = True, right_on='Journal', how = "inner")
merged.head()

       Cost_x                             Journal  Cost_y
0    0.000000  ACADEMY OF NUTRITION AND DIETETICS       1
1  433.593733                ACS CHEMICAL BIOLOGY       4
2    0.000000           ACS CHEMICAL NEUROSCIENCE       1
3   25.250000                            ACS NANO       2
4   16.891956              ACTA CRYSTALLOGRAPHICA       5

In [374]:
df_final = pd.DataFrame()
df_final['Journal'] = df_count['Journal']
df_final['Count'] = df_count['Cost']
df_final['Mean'] = df_mean['Cost']
df_final['Med'] = df_med['Cost']
#df_final['StDev'] = df_std['Cost'] -- ********Throws error. Why can't I use as_index = False on STDEV?*******

### Need to MERGE std dev cost column over to df_final (see above)
df_final['StDev'] = merged['Cost_x']

df_final = df_final.sort_values('Count', ascending = False)
df_final[ : 5]

,Journal,Count,Mean,Med,StDev
668,PLOS ONE,181,1994.896022,897.19,14211.649511
446,JOURNAL OF BIOLOGICAL CHEMISTRY,51,1426.778431,1314.53,411.311618
611,NEUROIMAGE,28,2230.718571,2335.04,253.163560
629,NUCLEIC ACIDS RESEARCH,25,1160.880000,852.00,438.778698
669,PLOS PATHOGENS,22,1572.866818,1600.25,158.061293

In [376]:
#ALTERNATE SOLUTION#

import numpy as np
result = df5.groupby('Journal', as_index=False).agg([np.count_nonzero,
                                                       np.mean, 
                                                       np.median, 
                                                       lambda x: np.std(x, ddof=0)])

#result.head()

#Try renaming the column
#result['Cost']['<lambda>'].name = 'Std Dev'
#result.head()
# Did not work... but did not throw error either?

In [367]:
#final = pd.DataFrame()
#final['Journal'] = result['Journal']
x = result['Cost'].sort_values(['count_nonzero'], ascending = False)
#print(result['Cost']['count_nonzero'].sort())
#final = result.sort_values('count_nonzero', ascending = False)

#Final outcome...
x[:5]

,count_nonzero,mean,median,<lambda>
Journal,,,,
PLOS ONE,181.0,1994.896022,897.19,14211.649511
JOURNAL OF BIOLOGICAL CHEMISTRY,51.0,1426.778431,1314.53,411.311618
NEUROIMAGE,28.0,2230.718571,2335.04,253.163560
NUCLEIC ACIDS RESEARCH,25.0,1160.880000,852.00,438.778698
PLOS PATHOGENS,22.0,1572.866818,1600.25,158.061293

In [ ]:
# In summary, either method I used to try to get the top 5, mean, med, std is valid